### PR TITLE
Added Favicon in Title Bar

### PR DESCRIPTION
**Pull request by K-Kumar-01**
### Closes Issue #164 

Added the favicon logo 

### Screenshots
DeepinScreenshot_20201219203804

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks! This will only work though when you open the website index page - if you open for example the `/download` page, you won't have the favicon? Should it be factored in a function that is called in each page?

**Comment by 4ian** [comment]
(something like `renderWebMonetizationMeta`, which is actually not used - but you get the idea)

**Comment by K-Kumar-01** [comment]
> Thanks! This will only work though when you open the website index page - if you open for example the `/download` page, you won't have the favicon? Should it be factored in a function that is called in each page?

@4ian
Well, the icon is present in all, as react helmet only sees the tags which are different in header files. The rest is taken from the index file as far as I know about it.
Attaching a screenshot for reference.
DeepinScreenshot_20201220225324
Let me know if any changes still need to be made :)

**Comment by 4ian** [comment]
Well that's the issue, the icon is not there for this page:
image

> The rest is taken from the index file as far as I know about it.

I don't think so, this is just some component like any other in React, no reasons things are somehow reused from the index file. 
That's why we need to factor this in a single function. We could rename `renderWebMonetizationMeta` into `renderHeadMeta` and use this function which should be already on all pages :)

**Comment by K-Kumar-01** [comment]
> Well that's the issue, the icon is not there for this page:
> image
> 
> > The rest is taken from the index file as far as I know about it.
> 
> I don't think so, this is just some component like any other in React, no reasons things are somehow reused from the index file.
> That's why we need to factor this in a single function. We could rename `renderWebMonetizationMeta` into `renderHeadMeta` and use this function which should be already on all pages :)

I am not able to understand. The icon is present in the title bar it seems to me. Is the icon not there when the site is build or something other

**Comment by 4ian** [comment]
By bad I looked at the wrong part! Sorry :)

Can you confirm that if you:
- open an Incognito window
- open `localhost:8000/download`
- then you see the favicon?

Thanks! :)

**Comment by K-Kumar-01** [comment]
> By bad I looked at the wrong part! Sorry :)
> 
> Can you confirm that if you:
> 
> * open an Incognito window
> * open `localhost:8000/download`
> * then you see the favicon?
> 
> Thanks! :)

Well, the icon seems to be there in incognito mode too.
Attaching the screenshot for reference/
DeepinScreenshot_20201221011034

**Comment by 4ian** [comment]
Let's give this a try then! :)

**Pull request merged**
